version: "3.7"
services:
  app:
    build:
      args:
        user: oday
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ecommerce
    container_name: ecommerce-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ecommerce

  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: ecommerce_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ecommerce

  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge