name: K8s Pipeline

on:
  push:
    branches:
      - master # Change this to your default branch
  workflow_dispatch:

jobs:
  Build-Docker-Image:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Docker login
          run: docker login -u mahmoudabdelaziz22 -p 3Oday54331666
        - name: Build ecommerce image
          run: docker build --build-arg user=oday --build-arg uid=1000 -f Dockerfile -t mahmoudabdelaziz22/ecommerce .
        - name: Push image
          run: docker push mahmoudabdelaziz22/ecommerce
          
  Deploy-K8s:
      runs-on: ubuntu-latest
      container:
          image: mahmoudabdelaziz22/mrmandoob-kubectl:latest
    #      options: --privileged  # Optional: Add privileged mode if needed
          
      needs: ["Build-Docker-Image"]
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: list repo
          run: ls -al
        - name: kubectl
          run: kubectl get nodes
        - name: Deploy K8s
          run: kubectl apply -R -f ./k8s
